apiVersion: apps/v1
kind: Deployment
metadata:
  name: proget-deployment
  namespace: proget
  labels:
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: proget
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proget
  template:
    metadata:
      namespace: proget
      labels:
        app.kubernetes.io/managed-by: manual
        app.kubernetes.io/name: proget
        azure.workload.identity/use: "true"
    spec:
      containers:
      - name: proget
        image: proget.inedo.com/productimages/inedo/proget:23.0.23
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        envFrom:
        - secretRef:
            name: proget-sql-connection-string
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: PROGET_SQL_CONNECTION_STRING
              key: azure-proget-poc-sql-connection-string
        resources:
          limits:
            cpu: '1'
            memory: 1000Mi
          requests:
            cpu: '1'
            memory: 1000Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - proget
            topologyKey: kubernetes.io/hostname
      serviceAccountName: workload-identity-sa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: proget-service
  namespace: proget
  labels:
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: proget
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/name: proget
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
