apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-proget-poc-msi
  namespace: ${NAMESPACE}
spec:
  provider: azure
  parameters:
    cloudName: ""
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    tenantId: ${IDENTITY_TENANT}
    keyvaultName: ${KEYVAULT_NAME}
    userAssignedIdentityID: ${USER_ASSIGNED_IDENTITY_ID}
    objects: |
      array:
        - |
          objectName: aks-proget-poc-sql-connection-string
          objectType: secret
          objectVersion: ""
  secretObjects:
  - data:
    - key: PROGET_SQL_CONNECTION_STRING
      objectName: aks-proget-poc-sql-connection-string
    type: Opaque
