apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: alpine
spec:
  containers:
  - image: alpine:3.1
    command:
    - /bin/sh
    - "-c"
    - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
